[project]
name = "position-tracking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "marysia-pm", email = "m.puciatamro@student.uw.edu.pl" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "opencv-python>=5.0.0.93",
]

[project.scripts]
position-tracking = "position_tracking:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
